import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import SnowLayer from "@/components/ui/SnowLayer";


// app/layout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <head>
        {/* lets the app use the full visual viewport (iOS safe areas too) */}
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />
        {/* ⭐ Telegram Mini App Script (MUST BE HERE) */}
        <script src="https://telegram.org/js/telegram-web-app.js"></script>
      </head>
      <body className="h-full overflow-hidden bg-black selection:bg-cyan-500/30 touch-none overscroll-none">
        <Providers>
          <SnowLayer />
          {children}
        </Providers>
      </body>
    </html>
  );
}


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


