import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SWRConfig } from "swr";
import { fetcher } from "@/lib/swrFetcher";


// app/layout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <head>
        {/* lets the app use the full visual viewport (iOS safe areas too) */}
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        {/* ⭐ Telegram Mini App Script (MUST BE HERE) */}
        <script src="https://telegram.org/js/telegram-web-app.js"></script>
      </head>
      <body className="h-full overflow-hidden bg-black">
        <SWRConfig
          value={{
            fetcher,
            dedupingInterval: 3000, // 3s prevent spam calls
            revalidateOnFocus: false,
            shouldRetryOnError: true,
            errorRetryInterval: 5000, // avoid hammering backend
          }}
        >
          {children}
        </SWRConfig>
      </body>
    </html>
  );
}


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


